// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var logger, settings;
    if (typeof exports === "undefined") {
      throw new Error("settings-development.js must be loaded as a module.");
    }
    logger = require("logging");
    settings = {
      env: "development",
      redis_host: "127.0.0.1",
      redis_port: 6379,
      node_port: 9228,
      node_host: "localhost:9229",
      node_scheme: "http://",
      num_node_process: 1,
      appname: "vids",
      appheadline: "share videos from your phone",
      max_upload_mb: 1000
    };
    module.exports = settings;
  })();

}).call(this);
